### ISSUE TITLE
Nothing happens when launching add-on

### ISSUE THREAD

**Issue by tooandrew** [dodslaser/script.moonlight-osmc#8]
Moonlight-embedded and moonlight-osmc are installed and working when launched through ssh (but only useable if I exit kodi, and even then only for a short while until kodi opens again) and the add-on is configured correctly. However, literally nothing happens when  I launch the addon, and I'm at a loss. running the 20151129 build of osmc on a model b+.

**Comment by dodslaser** [comment]
Try  addon `dtparam=audio=on` to */boot/config.txt* and reboot.
